In [15]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
#import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
pow(np.ones(20, dtype='int64')*2,np.arange(1,21,dtype='int64'))/np.arange(1,21,dtype='int64')

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [10]:
np.sum(pow(np.ones(6)*0.1, np.arange(0, 18, 3)) * pow(np.ones(6)*0.2,np.arange(0, 24, 4)))


1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [7]:
a = np.zeros((8,8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [94]:
X = np.random.random((5, 2))
np.array((pow((X*X).sum(axis = 1), 1/2), np.arctan(X[:, 0]/X[:, 1]))).T

array([[1.10747386, 1.12563969],
       [0.85381143, 1.15720031],
       [0.13687745, 0.9214933 ],
       [0.90719582, 0.15732569],
       [0.47091304, 1.10125566]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [118]:
X = np.random.random((10, 10))
np.unravel_index(np.argmax(X), X.shape)

(8, 7)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [144]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

X[np.argmin(pow(pow((X[:, 0] - y[:,0]), 2) + pow((X[:, 1] - y[:,1]),2), 1/2)), :]

array([0.50592141, 0.27253976])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [38]:
a = (pow(np.arange(-3, 0, 1), 2) + np.arange(-3, 0, 1)*2 + 6)
b = (np.arange(0, 3, 1) + 6)
c = (pow(np.array([2, 3]), 2) + np.array([2, 3])*2 - 4)
np.concatenate((a,b,c))


array([ 9,  6,  5,  6,  7,  8,  4, 11])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [55]:
X = np.random.random((10, 10))
#X = np.arange(1,10).reshape(3,3)
a = X - np.mean(X, axis = 1).reshape(10,1)
#np.mean(a, axis = 1)

## your code

array([ 7.77156117e-17,  0.00000000e+00, -1.66533454e-16,  1.33226763e-16,
        4.44089210e-17,  5.55111512e-17,  5.55111512e-17,  0.00000000e+00,
       -4.44089210e-17,  1.22124533e-16])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [110]:
X = np.random.normal(loc=5, scale=2., size=1000)
m = np.mean(X)
d = np.mean(pow(X,2)) - pow(m, 2)
print(m, d)

4.929358015707818 3.800465439187299


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [51]:
a = np.zeros((5, 5)) + np.arange(5)
a[1,:] = np.roll(a[1,:], -1)
a[2,:] = np.roll(a[2,:], -2)
a[3,:] = np.roll(a[3,:], -3)
a[4,:] = np.roll(a[4,:], -4)
a

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [115]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 6)    

[4, 0, 4, 0, 4, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [46]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    val = s*np.random.random(c)
    cs = np.repeat(np.cumsum(x), c).reshape((len(x), c)).astype("float32")
    cs -= val
    cs[cs > 0] = 0
    return np.argmax(cs, axis=0)
    
    
sample([50, 3, 1, 7, 20], 6)  

array([4, 0, 3, 4, 0, 0], dtype=int64)